### PR TITLE
WIP: Fix unscaped output

### LINKED ISSUE #9: laterpay/views/frontend/partials/widget/explanatory-overlay.php
Unescaped output:

```
echo $overlay_data['action']
```

### PR DESCRIPTION
**Pull request by PatelUtkarsh**
Fixes #9 

WIP because of the open question.

### CODE REVIEW

File: laterpay/views/frontend/partials/widget/explanatory-overlay.php [hunk 1]
```diff
@@ -36,7 +36,23 @@
                 <?php
                     // ignoring this because generated html is escaped in,
                     // views/frontend/partials/widget/purchase-button.php
-                    echo $overlay_data['action']; // phpcs:ignore
+                echo wp_kses( $overlay_data['action_html_escaped'], [
```
Comment (PatelUtkarsh) [inline laterpay/views/frontend/partials/widget/explanatory-overlay.php:39]: Since we know the output is escaped and I changed the key name, will it work without using `wp_kses` here? @tomjn

Comment (tomjn) [reply laterpay/views/frontend/partials/widget/explanatory-overlay.php:39]: It should do but since the wp_kses call is already here i see no harm in keeping it anyway

**Review by tomjn — APPROVED** [review]
